// CSSStyleDeclaration对象
CSSStyleDeclaration = function CSSStyleDeclaration(){return ldvm.toolsFunc.throwError("TypeError","Illegal constructor");}
ldvm.toolsFunc.safeProto(CSSStyleDeclaration,"CSSStyleDeclaration");
ldvm.toolsFunc.defineProperty(CSSStyleDeclaration.prototype,"cssText",{configurable:true,enumerable:true, get: function (){return ldvm.toolsFunc.dispatch(this,CSSStyleDeclaration.prototype,"CSSStyleDeclaration","cssText_get",arguments)}, set: function (){return ldvm.toolsFunc.dispatch(this,CSSStyleDeclaration.prototype,"CSSStyleDeclaration","cssText_set",arguments)}});
ldvm.toolsFunc.defineProperty(CSSStyleDeclaration.prototype,"length",{configurable:true,enumerable:true, get: function (){return ldvm.toolsFunc.dispatch(this,CSSStyleDeclaration.prototype,"CSSStyleDeclaration","length_get",arguments)}, set: undefined});
ldvm.toolsFunc.defineProperty(CSSStyleDeclaration.prototype,"parentRule",{configurable:true,enumerable:true, get: function (){return ldvm.toolsFunc.dispatch(this,CSSStyleDeclaration.prototype,"CSSStyleDeclaration","parentRule_get",arguments)}, set: undefined});
ldvm.toolsFunc.defineProperty(CSSStyleDeclaration.prototype,"cssFloat",{configurable:true,enumerable:true, get: function (){return ldvm.toolsFunc.dispatch(this,CSSStyleDeclaration.prototype,"CSSStyleDeclaration","cssFloat_get",arguments)}, set: function (){return ldvm.toolsFunc.dispatch(this,CSSStyleDeclaration.prototype,"CSSStyleDeclaration","cssFloat_set",arguments)}});
ldvm.toolsFunc.defineProperty(CSSStyleDeclaration.prototype,"getPropertyPriority",{configurable:true,enumerable:true, writable:true, value: function (){return ldvm.toolsFunc.dispatch(this,CSSStyleDeclaration.prototype,"CSSStyleDeclaration","getPropertyPriority",arguments)}});
ldvm.toolsFunc.defineProperty(CSSStyleDeclaration.prototype,"getPropertyValue",{configurable:true,enumerable:true, writable:true, value: function (){return ldvm.toolsFunc.dispatch(this,CSSStyleDeclaration.prototype,"CSSStyleDeclaration","getPropertyValue",arguments)}});
ldvm.toolsFunc.defineProperty(CSSStyleDeclaration.prototype,"item",{configurable:true,enumerable:true, writable:true, value: function (){return ldvm.toolsFunc.dispatch(this,CSSStyleDeclaration.prototype,"CSSStyleDeclaration","item",arguments)}});
ldvm.toolsFunc.defineProperty(CSSStyleDeclaration.prototype,"removeProperty",{configurable:true,enumerable:true, writable:true, value: function (){return ldvm.toolsFunc.dispatch(this,CSSStyleDeclaration.prototype,"CSSStyleDeclaration","removeProperty",arguments)}});
ldvm.toolsFunc.defineProperty(CSSStyleDeclaration.prototype,"setProperty",{configurable:true,enumerable:true, writable:true, value: function (){return ldvm.toolsFunc.dispatch(this,CSSStyleDeclaration.prototype,"CSSStyleDeclaration","setProperty",arguments)}});

